import { dieArray } from '@/composables/dice';

export const PLACE_TEMPLATE: string[] = [
  'The [place] ',
  'The [adjective] [place] ',
  'The [place] of (the) [noun] ',
  '(The) [noun]’s [place]',
  '[place] of the [adjective] [noun]',
  'The [adjective] [noun]',
];
export const PLACE_PLACE: string[] = [
  'Barrier',
  'Beach',
  'Bowl',
  'Camp',
  'Cave',
  'Circle',
  'City',
  'Cliff',
  'Crater',
  'Crossing',
  'Crypt',
  'Den',
  'Ditch',
  'Falls',
  'Fence',
  'Field',
  'Fort',
  'Gate',
  'Grove',
  'Hill',
  'Hole',
  'Hut',
  'Keep',
  'Lake',
  'Marsh',
  'Meadow',
  'Mountain',
  'Pit',
  'Post',
  'Ridge',
  'Ring',
  'Rise',
  'Road',
  'Rock',
  'Ruin',
  'Shrine',
  'Spire',
  'Spring',
  'Stone',
  'Tangle',
  'Temple',
  'Throne',
  'Tomb',
  'Tower',
  'Town',
  'Tree',
  'Vale',
  'Valley',
  'Village',
  'Wall',
];
export const PLACE_ADJECTIVE: string[] = [
  'Ancient',
  'Ashen',
  'Black',
  'Bloody',
  'Blue',
  'Bright',
  'Broken',
  'Burning',
  'Clouded',
  'Copper',
  'Cracked',
  'Dark',
  'Dead',
  'Doomed',
  'Endless',
  'Fallen',
  'Far',
  'Fearsome',
  'Floating',
  'Forbidden',
  'Frozen',
  'Ghostly',
  'Gloomy',
  'Golden',
  'Grim',
  'Hidden',
  'High',
  'Iron',
  'Jagged',
  'Lonely',
  'Lost',
  'Low',
  'Near',
  'Petrified',
  'Red',
  'Screaming',
  'Sharp',
  'Shattered',
  'Shifting',
  'Shining',
  'Shivering',
  'Shrouded',
  'Silver',
  'Stalwart',
  'Stoney',
  'Sunken',
  'Thorny',
  'Thundering',
  'White',
  'Withered',
];
export const PLACE_NOUN: string[] = [
  '[Name]*',
  'Arm',
  'Ash',
  'Blood',
  'Child',
  'Cinder',
  'Corpse',
  'Crystal',
  'Dagger',
  'Death',
  'Demon',
  'Devil',
  'Doom',
  'Eye',
  'Fear',
  'Finger',
  'Fire',
  'Foot',
  'Ghost',
  'Giant',
  'Goblin',
  'God',
  'Gold',
  'Hand',
  'Head',
  'Heart',
  'Hero',
  'Hope',
  'King',
  'Knave',
  'Knight',
  'Muck',
  'Mud',
  'Priest',
  'Queen',
  'Sailor',
  'Silver',
  'Skull',
  'Smoke',
  'Souls',
  'Spear',
  'Spirit',
  'Stone',
  'Sword',
  'Thief',
  'Troll',
  'Warrior',
  'Water',
  'Witch',
  'Wizard',
];

export const generatePlaceName = () => {
  const template = dieArray(PLACE_TEMPLATE);
  const place = dieArray(PLACE_PLACE);
  const adjective = dieArray(PLACE_ADJECTIVE);
  const noun = dieArray(PLACE_NOUN);

  return template
    .replace('[place]', `<span class="small-caps">${place}</span>`)
    .replace('[adjective]', `<span class="small-caps">${adjective}</span>`)
    .replace('[noun]', `<span class="small-caps">${noun}</span>`);
};
